### ISSUE TITLE
URGENT: add pom action to create an assembly jar

### ISSUE THREAD

**Issue by egonw** [bridgedb/bridgedb-webservice#4]

**Comment by egonw** [comment]
Implemented but the Derby `ClientDriver` is not found on the classpath. Tried to debug it, but yet without success and keep running into this exception:

```
org.bridgedb.IDMapperException: Could not connect to database: No suitable driver found for jdbc:derby:jar:(/home/egonw/Downloads/bdb/Hs_Derby_Ensembl_91.bridge)database
        at org.bridgedb.rdb.SimpleGdbFactory.createInstance(SimpleGdbFactory.java:64)
        at org.bridgedb.rdb.IDMapperRdb$DriverPgdb.connect(IDMapperRdb.java:57)
        at org.bridgedb.BridgeDb.connect(BridgeDb.java:54)
        at org.bridgedb.rdb.GdbProvider.fromConfigFile(GdbProvider.java:156)
        at org.bridgedb.server.IDMapperService.connectGdbs(IDMapperService.java:321)
        at org.bridgedb.server.IDMapperService.start(IDMapperService.java:243)
        at org.restlet.routing.Filter.start(Filter.java:274)
        at org.restlet.routing.Router.start(Router.java:887)
        at org.restlet.Component.startRouters(Component.java:588)
        at org.restlet.Component.start(Component.java:532)
        at org.bridgedb.server.Server.run(Server.java:49)
        at org.bridgedb.server.Server.main(Server.java:109)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:derby:jar:(/home/egonw/Downloads/bdb/Hs_Derby_Ensembl_91.bridge)database
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
        at org.bridgedb.rdb.SimpleGdbFactory.createInstance(SimpleGdbFactory.java:59)
        ... 11 more
```

when I run the code with `java -jar org.bridgedb.server/target/bridgedbServer-jar-with-dependencies.jar`. However, when I run `java -cp org.bridgedb.server/target/bridgedbServer-jar-with-dependencies.jar:derby-10.15.2.0.jar:derbyclient-10.15.2.0.jar org.bridgedb.server.Server`, then the `ClientDriver` is found without problems.

I have yet to find out how I can have the BridgeDb code figure out how to run https://github.com/bridgedb/BridgeDb/blob/50da029af3b6fed31c77f6ae7e15d3d981b3c739/org.bridgedb.rdb/src/org/bridgedb/rdb/IDMapperRdb.java#L93 without problems...

**Comment by egonw** [comment]
An update is in order. We've been working on updating the dependencies of the webservice, while at the same time add JSON support. This is progressing well, and the latest news is that the Docker is now working with the latest code. This has yet to be merged in, I belief, but we're soon able to close this issue.

**Comment by egonw** [comment]
Fixed in https://github.com/bridgedb/BridgeDbWebservice
